wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1648822482
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 16
      4: 3.8.10
      5: 0.12.11
      8:
      - 5
batch_size:
  desc: null
  value: 64
checkpoint_dir:
  desc: null
  value: models
cuda:
  desc: null
  value: false
do_predict:
  desc: null
  value: true
do_train:
  desc: null
  value: true
do_val:
  desc: null
  value: true
epochs:
  desc: null
  value: 10
input_num:
  desc: null
  value: 48
learning_rate:
  desc: null
  value: 0.001
log_step:
  desc: null
  value: 100
momentum:
  desc: null
  value: 0.9198
num_ae_hidden1:
  desc: null
  value: 150
num_ae_hidden2:
  desc: null
  value: 80
num_ae_hidden3:
  desc: null
  value: 60
num_ae_hidden4:
  desc: null
  value: 40
num_ae_output:
  desc: null
  value: 10
num_ae_output1:
  desc: null
  value: 30
out_file_path:
  desc: null
  value: ../../20/autoencoder_compressed.csv
output_num:
  desc: null
  value: 5
train_file_path:
  desc: null
  value: ../../20/dataset1.csv
use_trained:
  desc: null
  value: true
val_batch_size:
  desc: null
  value: 64
val_file_path:
  desc: null
  value: ../../20/dataset1.csv
wandb:
  desc: null
  value: false
weight_decay:
  desc: null
  value: 0.01
