wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1649264839
    t:
      1:
      - 1
      - 5
      - 41
      2:
      - 1
      - 5
      - 41
      3:
      - 16
      4: 3.8.10
      5: 0.12.11
      8:
      - 5
autoencoder_compressed_path:
  desc: null
  value: ../../20/autoencoder_compressed.csv
batch_size:
  desc: null
  value: 64
checkpoint_dir:
  desc: null
  value: models
cuda:
  desc: null
  value: false
do_predict:
  desc: null
  value: true
do_train:
  desc: null
  value: true
do_val:
  desc: null
  value: true
epochs:
  desc: null
  value: 100
input_num:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0001
log_step:
  desc: null
  value: 100
momentum:
  desc: null
  value: 0.9198
num_hidden1:
  desc: null
  value: 25
num_hidden2:
  desc: null
  value: 19
output_num:
  desc: null
  value: 5
pca_compressed_path:
  desc: null
  value: ../../20/pca_compressed.csv
use_autoencoder:
  desc: null
  value: true
use_trained:
  desc: null
  value: true
val_batch_size:
  desc: null
  value: 64
wandb:
  desc: null
  value: false
weight_decay:
  desc: null
  value: 0.0
