wandb_version: 1

batch_size:
  value: 116
epochs:
  value: 161
learning_rate:
  value: 0.007439544575393058
momentum:
  value: 1.2781694338261778
num_ae_hidden1:
  value: 34
num_ae_hidden2:
  value: 18
