wandb_version: 1

batch_size:
  value: 182
epochs:
  value: 190
learning_rate:
  value: 0.014593538265897533
momentum:
  value: 0.7898283271405888
num_ae_hidden1:
  value: 30
num_ae_hidden2:
  value: 34
