wandb_version: 1

batch_size:
  value: 48
epochs:
  value: 122
learning_rate:
  value: 0.011924364491045874
momentum:
  value: 1.3848118189555558
num_ae_hidden1:
  value: 14
num_ae_hidden2:
  value: 24
