wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1647890553
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 13
      - 16
      4: 3.8.10
      5: 0.12.11
      8:
      - 5
batch_size:
  desc: null
  value: 1
checkpoint_dir:
  desc: null
  value: models_v2
cuda:
  desc: null
  value: false
do_predict:
  desc: null
  value: true
do_train:
  desc: null
  value: true
do_val:
  desc: null
  value: true
epochs:
  desc: null
  value: 100
file_path:
  desc: null
  value: /Users/tanay/Documents/sem6/CS6910/20/task1/func_app2.csv
input_num:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 1.19e-05
model_path:
  desc: null
  value: /Users/tanay/Documents/sem6/CS6910/code1/models_v2/models.ckpt
momentum:
  desc: null
  value: 0.9704
num_hidden1:
  desc: null
  value: 22
num_hidden2:
  desc: null
  value: 14
output_num:
  desc: null
  value: 1
use_trained:
  desc: null
  value: true
val_batch_size:
  desc: null
  value: 1
wandb:
  desc: null
  value: false
