wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1647361952
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 13
      - 16
      4: 3.8.10
      5: 0.12.11
      8:
      - 5
batch_size:
  desc: null
  value: 1
checkpoint_dir:
  desc: null
  value: models
cuda:
  desc: null
  value: false
do_predict:
  desc: null
  value: true
do_train:
  desc: null
  value: true
do_val:
  desc: null
  value: true
epochs:
  desc: null
  value: 1
input_num:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 9.2e-05
momentum:
  desc: null
  value: 0.9198
num_hidden1:
  desc: null
  value: 13
num_hidden2:
  desc: null
  value: 18
output_num:
  desc: null
  value: 1
train_file_path:
  desc: null
  value: ../20/task2a/train_t20.csv
use_trained:
  desc: null
  value: true
val_batch_size:
  desc: null
  value: 1
val_file_path:
  desc: null
  value: ../20/task2a/dev_t20.csv
wandb:
  desc: null
  value: false
