wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1649266537
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 16
      4: 3.8.10
      5: 0.12.11
      8:
      - 5
checkpoint_dir:
  desc: null
  value: models
input_num:
  desc: null
  value: 48
out_file_path:
  desc: null
  value: ../../20/pca_compressed.csv
output_num:
  desc: null
  value: 10
train_file_path:
  desc: null
  value: ../../20/dataset1.csv
val_file_path:
  desc: null
  value: ../../20/dataset1.csv
